default_context:
  project_name: 'Militariaku'
  project_slug: 'militariaku'
  domain_main: 'militariaku.com'
  domain_staging: 'stag.militariaku.com'
  docker_swarm_stack_name_main: 'militariaku-com'
  docker_swarm_stack_name_staging: 'stag-militariaku-com'
  secret_key: 'secret'
  first_superuser: 'admin@militariaku.com'
  first_superuser_password: 'jalalAzhmatkhan94'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.militariaku.com", "https://stag.militariaku.com", "https://militariaku.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@militariaku.com'
  postgres_password: 'jalalAzhmatkhan94'
  pgadmin_default_user: 'admin@militariaku.com'
  pgadmin_default_user_password: 'jalalAzhmatkhan94'
  traefik_constraint_tag: 'militariaku.com'
  traefik_constraint_tag_staging: 'stag.militariaku.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:jalalAzhmatkhan94'
  sentry_dsn: ''
  docker_image_prefix: 'militariaku_'
  docker_image_backend: 'militariaku_BACKEND'
  docker_image_celeryworker: 'militariaku_CELERYWORKER'
  docker_image_frontend: 'militariaku_FRONTEND'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
